language: generic
sudo: required
services:
 - docker

before_install:
  - docker build -t mikeaws1/react-test -f client/Dockerfile.dev ./client
  

script:
  - docker run -e CI=true mikeaws1/react-test npm test


after_success:
  - docker build -t mikeaws1/multi-client ./client
  - docker build -t mikeaws1/multi-nginx ./ngnix
  - docker build -t mikeaws1/multi-server ./server
  - docker build -t mikeaws1/multi-worker ./worker
# Push to docker hub
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_ID} --password-stdin
  - docker push mikeaws1/multi-client
  - docker push mikeaws1/multi-nginx
  - docker push mikeaws1/multi-server
  - docker push mikeaws1/multi-worker



