language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- docker build -t mikeaws1/react-test -f client/Dockerfile.dev ./client
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
script:
- docker run -e CI=true mikeaws1/react-test npm test
after_success:
- docker build -t mikeaws1/multi-client ./client
- docker build -t mikeaws1/multi-nginx ./ngnix
- docker build -t mikeaws1/multi-server ./server
- docker build -t mikeaws1/multi-worker ./worker
- echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_ID} --password-stdin
- docker push mikeaws1/multi-client
- docker push mikeaws1/multi-nginx
- docker push mikeaws1/multi-server
- docker push mikeaws1/multi-worker
deploy:
  provider: script
  script: sh deploy.sh ${DOCKER_HUB}
  on:
    branch: master
